<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Compiler.CodeGen.x86\Compiler.CodeGen.x86.csproj" />
      <ProjectReference Include="..\Compiler.Frontend\Compiler.Frontend.csproj" />
      <ProjectReference Include="..\Compiler.IR\Compiler.IR.csproj" />
      <ProjectReference Include="..\Compiler.Lowering\Compiler.Lowering.csproj" />
      <ProjectReference Include="..\Compiler.Semantic\Compiler.Semantic.csproj" />
    </ItemGroup>

</Project>
