<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Compiler.CodeGen</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Compiler.IR\Compiler.IR.csproj" />
    </ItemGroup>

</Project>
